name: Code Coverage Comment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  comment:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    name: 'Comment Code Coverage'
    runs-on: ubuntu-latest
    steps:
      - uses: Nef10/comment-lcov-action@dd416bb982e751bc3f044136d018e31358f66b90
